### ISSUE TITLE
Email App.

### ISSUE THREAD

**Issue by reyunami** [adrian-bl-yuga/device-sony-c6603#1]
Sir the email app unfortunately stop..:) and i have a concern about the calendar. Their are 2 calendar sin the apps drawer the aosp calendar and google calendar. Can you make a script to your gapps to replace the aosp calendar after flashing so that the calendar will be only one.:) sorry for my poor english..your rom is awesome. Thnks in advance.

**Comment by hugo19941994** [comment]
You can disable the AOSP calendar app (and others) by going to settings/apps/all/calendar and pressing disable.

**Comment by adrian-bl-yuga** [comment]
E-Mail will be fixed in the next release, and as hugo19941994 already said: you can disable the 2nd calendar (this has been a standard android feature since 4.0)

**Comment by reyunami** [comment]
Ohh sorry. I forgot that disable settings.:).thanks for your reply.about email ok we will wait the fix thnk you for this wonderful rom. You are a great developer. :)
