### ISSUE TITLE
Google Now voice commands too quiet

### ISSUE THREAD

**Issue by patrick-brigel** [adrian-bl-yuga/device-sony-c6603#11]
It seems like that the internal microphone used for Google Now is too quiet. Only yelling "Ok Google" activates it.

**Comment by adrian-bl-yuga** [comment]
works for me.

**Comment by patrick-brigel** [comment]
I made a comparison between my Nexus 4 and the Xperia Z. It's still present.
https://www.youtube.com/watch?v=g0iuFcTqzDc
