### ISSUE TITLE
Wifi issuse

### ISSUE THREAD

**Issue by solomajestiks** [adrian-bl-yuga/device-sony-c6603#14]
Wifi don't recognize wifi's on high channels like 10 or 12

**Comment by adrian-bl-yuga** [comment]
Uhm: no: My own WIFI runs on Channel 13 and it works perfectly.

Please post the output of

adb shell cat /proc/version
..and..
adb shell 'dmesg | grep ieee80211'

**Comment by solomajestiks** [comment]
i really can't do it, i every time become the error device is offline

**Comment by adrian-bl-yuga** [comment]
Closing this bug due to the lack of any logfiles.
