### ISSUE TITLE
Google Backup Transport does not work

### ISSUE THREAD

**Issue by hexchain** [adrian-bl-yuga/device-sony-c6603#17]
Steps to reproduce:
1. Full wipe
2. Install ROM and Google Apps as stated [here](http://www.blinkenlights.ch/ccms/android/yuga-l.html)
3. Set up account and enable "Backups"

Then a toast comes up saying "Couldn't restore from backup", and in "Backup & restore" settings "Backup account" defaults to "local private backup" and is not selectable.

Logcat: https://paste.xinu.at/FCL0o/ (Useful lines should be around L750, but I'm not quite sure)

My workaround:
1. Start an ADB shell
2. Enter `bmgr list transports`. Output should be identical to the following:

```
    com.google.android.backup/.BackupTransportService
  * android/com.android.internal.backup.LocalTransport
```
1. Enter `bmgr transport com.google.android.backup/.BackupTransportService`
2. Enter `bmgr list sets` and choose the correct set you want to restore from, remember the hex-digit token
3. Enter `bmgr restore <TOKEN_FROM_STEP4>` to trigger a full restore.

This works for me, as can be seen that wallpaper and desktop icons are restored.

**Comment by alex3305** [comment]
Maybe it is a possibility to include the `bmgr transport com.google.android.backup/.BackupTransportService` in the GApps installation script, just after installing GApps? Because I think that Google backup will automatically work when doing the first time setup..

**Comment by adrian-bl-yuga** [comment]
Hmm.. this is a little bit tricky:

AOSP includes a config option to define the default transport (and, by default, uses the internal dummy transport). However: There can only be ONE transport defined and specifing a transport that may not exist (gapps may not be installed) is out of question.

Including this in the gapps installation script sounds like a good idea - but on the other hand i dislike automatic configuration changes.

Maybe we should just include the required adb command into the gapps installation instructions?

**Comment by hexchain** [comment]
I'm not quite a ROM dev, but still wonder how did this work in 4.4 days? People just flash GApps package and setup their account, and everything works. Is there any specific hack in use?

**Comment by alex3305** [comment]
Unfortunately the Google Backup Transport didn't work in 4.4 either. Which wasn't really an issue for me though.

@adrian-bl-yuga I think you have a valid point. Although I think that when you install GApps you can also expect having the Google Backup available to you by default. But that's just my humble opinion.

**Comment by adrian-bl-yuga** [comment]
I'm closing this bug as the instructions on how to enable googles backup transport have been added to the 'installing gapps' documentation.

**Comment by hexchain** [comment]
On Dec 27, 2014 11:18 PM, "Adrian Ulrich" notifications@github.com wrote:

> I'm closing this bug as the instructions on how to enable googles backup
> transport have been added to the 'installing gapps' documentation.

I think people should also know how to restore from an existing Google
backup. So could you please add that as well?

**Comment by adrian-bl** [comment]
I never used the google backup transport myself - but shouldn't it automatically restore after the transport has been choosen?

**Comment by hexchain** [comment]
Doesn't seem so, at lease for me it didn't until I manually triggered a restore.

**Comment by adrian-bl** [comment]
hmm, ok: i added the restore steps to the installations instructions.

thanks for documenting this!
