### ISSUE TITLE
Email doesn't synchronize

### ISSUE THREAD

**Issue by jpacho89** [adrian-bl-yuga/device-sony-c6603#18]
Hi Adrian,
Hi have some issues with AOSP email app. When I  choose to synchronize the accounts in system settings all works perfect, but after an hours, it disables all synchronizations, and I have to enable them again.. Have you experience same behaviour? If not, I will provide you a log if needed. I made clean install of 5.0.4

**Comment by adrian-bl-yuga** [comment]
No, this works for me (however: i'm not a very heavy user of the app)

But the AOSP E-Mail app is in _very_ bad shape: I even had to patch it to avoid a crash during the account setup: Nobody at google ever tested it before releasing it.

Given this, i would not be surprised if there are more bugs. I would threfore recommend to install the market-gmail app or K9 (if you are using imap).

Push in K9 works perfectly: I'm using it everyday.

**Comment by jpacho89** [comment]
Ok thanks!
I will follow your advice ;)
