### ISSUE TITLE
video bug

### ISSUE THREAD

**Issue by sulemartin87** [adrian-bl-yuga/device-sony-c6603#2]
I found that when playing a video, it only plays for 1 second. The video stops but the audio keeps playing. It only starts playing normally when you seek to any part of the video and back to the start. tested on stock video player for the gallery and the Google photos app. noticed the issue on build 5.0.2, still exists on the 5.0.3 build.

**Comment by reyunami** [comment]
I tested mine multiple times but nothing issue like that. Im using 5.0.3. .:)

**Comment by sulemartin87** [comment]
Ok, a little update on the issue, i flashed the rom again deleting all data, the problem still persisted. Then i decided to flash the 5.0.1 build. This made the video play normally again. Flashed back the latest build and the video was gone again.

**Comment by zabi1994** [comment]
I've experienced this video bug too.. In chrome and in 3rd party apps.. I played Injustice and even on the WB logo splash the problem persist.. The FPS drops for a while before resuming content.. Same goes for video.. Does anyone know what the NuPlayer option is in developer options ? Can it in any way may have caused this issue ? Currently running version 5.0.3..

**Comment by zabi1994** [comment]
I've unticked the option of running experimental NuPlayer and so far the video bug seems to be gone.. Do tell if this method works for you guys too..

**Comment by adrian-bl-yuga** [comment]
I noticed this too and the issue seems definitely to be related to NuPlayer.
Does someone know if NuPlayer is also enabled by default on retail builds?

The reason why it works on 5.0.1 (and also sometimes on 5.0.3!) may be related to qc-fqd: It was broken on 5.0.1 and keept all 4 cores always running - maybe NuPlayer somehow thinks that the device is slow after the first few frames (if only one core is active) and goes int derp mode.

**Comment by xarive** [comment]
Sorry to say that this problem is also persists in aosp gallery video player.

**Comment by xarive** [comment]
Just tried YouTube app and the video seems playing at low framerate..

**Comment by sulemartin87** [comment]
disabling NuPlayer seems to have done the trick, back to glorious fps'.

**Comment by AdmiralRedRum** [comment]
Nuplayer thing is enabled automatically by default  if u activate developer options. We gonna need to ask someone without activated developer options to test videos

**Comment by xarive** [comment]
sorry I don't get clearly in my last post. I've not activated dev option and the video bug still persist. going to try to activate the dev option and see the difference.

**Comment by xarive** [comment]
one more thing is that the Nuplayer is enabled in native. I enabled the dev option and disable nuplayer and the video bug seems to be gone.

**Comment by adrian-bl-yuga** [comment]
Ok, this should be fixed in the next build (https://github.com/adrian-bl-yuga/kernel_10_4_B_0_569/commit/8a53a4e4d587053e8c2a5cf1309af51c0e3bd5d4)

In the meantime you can flash this boot.img (for 5.0.3): https://mega.co.nz/#!To0H3IBQ!NSJgNtB2svJJBZyTs0mdKodw6jS3IADhBj6OeZV8W58

**Comment by sulemartin87** [comment]
thank you so much, you are amazing.
