### ISSUE TITLE
playing music bug

### ISSUE THREAD

**Issue by ben-29** [adrian-bl-yuga/device-sony-c6603#21]
like nearly 10 times per minute,less than a sec break noise,but no allways,sometime it is ok
speaker,headset,bluetooth headset are the same
app: music,poweramp

**Comment by adrian-bl-yuga** [comment]
Closing this bug as it contains absolutely no valuable information.
- No logs provided
- Where is the music stored

Feel free to re-open once the information has been provided.

**Comment by ben-29** [comment]
the musics are in internal sd card,and there are playing well but sometimes with noising sounds,i don't know how to explain it well with my poor English :(

**Comment by ben-29** [comment]
for using 5.0.6 one week,i don't meet the issue anymore
