### ISSUE TITLE
Other bluetooth devices not listed

### ISSUE THREAD

**Issue by alex3305** [adrian-bl-yuga/device-sony-c6603#22]
Although pairing with bluetooth devices works like a charm, when I search for other bluetooth devices, no bluetooth devices are listed in the settings page.

I tried this with the following devices:
- Sony Xperia Z with stock 4.4
- Mi Band

Do others have the same issue? I miss this feature because this way Smart Lock cannot work.

**Comment by adrian-bl-yuga** [comment]
Smart-Lock with BT works fine for me: i'm using it with my moto360 and just tested it with a (newly paired) bt-mouse.

Did you actually pair with the device? SmartLock will only list already paired (and active!) devices

**Comment by alex3305** [comment]
I meant to say that I don't even see any devices to pair with in the Bluetooth settings screen. I just tried it with my Roadie tuner, Mi band and other Xperia Z (4.4) but I cannot seem to discovery any devices. They can discover and auto-pair with my phone perfectly though.

But because of this limitation I cannot use SmartLock. I will look into Logcat for any issues and add it to my post if it seems relevant.

**Comment by alex3305** [comment]
After testing it for a while and unpairing devices, I discovered that I can find devices to pair with, but only when they are discoverable when I start scanning with Bluetooth. This issue can thus be closed.
