### ISSUE TITLE
WiFi disconnects during sleep

### ISSUE THREAD

**Issue by sulemartin87** [adrian-bl-yuga/device-sony-c6603#24]
I have been experiencing an issue since build 4 where my wifi network would disconnect during sleep. I first thought it was a problem with my phone and decided to try a different ROM. I flashed the stock KitKat build and realized i never encountered this problem. after i skipped two builds, i decided to flash the 506 build. As soon as i flashed the ROM the problem resurfaced. Any and all help would be very welcome. P.S. i did change the wifi policies to never and back but to no avail.

**Comment by adrian-bl-yuga** [comment]
I noticed this too but do not think that it is related to any release:

The wifi policy itself is handled correctly but it seems like the device sometimes enters a state where it fails to automatically reconnect after the connection went down. (This may even happen if the device is placed near the AP as common 'plastic routers' can be very flaky)

**Comment by sulemartin87** [comment]
Thanks for your reply. I have been doing a bit of some digging and every time a problem like this arises on certain devices, it is usually caused by an app changing these setting without the users permission. I will have to analyze the possible apps and will definitely get back to you. If you do find a solution feel free to write at me.

**Comment by adrian-bl-yuga** [comment]
Hmm: I observed that android simply does not run periodic scans and therefore may not restore a lost connection to an AP:

I can reproduce the issue by connecting my phone to some other android hotspot, let it untouched for a few minutes and then toggle the hotspot on & off: The phone will not reconnect until the screen turns on (causing a network scan)

I'm acutally not quite sure if this is the expected behaviour or if android expects the driver to (magically) send a netlink message after the AP shows up again.

I'll keep an eye on this and will check if this also happened in 4.4.

In the worst case, i could so some ugly hack in the wifi-framework to trigger rescans if wifi is on but not connected.

**Comment by sulemartin87** [comment]
I ran a couple of tests in stock 4.4.4 and this problem did not show up, not once. I'll keep collecting data and keep reporting if anything i do appears to have changed anything.

**Comment by adrian-bl-yuga** [comment]
I was talking about my 4.4.4 build: If it works there, i could be sure that it is not an issue of the wifi driver

**Comment by sulemartin87** [comment]
oh OK. If you need me to help test your KitKat Build Let me Know.

**Comment by adrian-bl-yuga** [comment]
What happens if you _disable_ the 'scanning always available' feature in the advanced settings?

With this setting disabled, i see regular network scans (like in 4.4.4) while enabling it causes the background scans to stop after some time

**Comment by sulemartin87** [comment]
While all this was happening i had already disabled it. I had been trying different settings to try and pin it on a specific setting. This has yielded no results as of yet.

**Comment by sulemartin87** [comment]
Have you found a workaround as of yet?

**Comment by adrian-bl-yuga** [comment]
I know how i could work around the issue: the wificontroller receives updates about the battery level and i could change it to try a reconnect if the wifi is not connected.

However: I didn't get around to implement (+ test) this yet - maybe during christmas holidays.

**Comment by planarteapot** [comment]
I also had this issue, I think. I saw it like this: When going from work to home, or back again, my Z usually did not connect to the new Wifi, until I power cycled my phone. For example if Wifi working at work, then going home, I see a list of one Wifi network available - which is my work one. Happens even if I turn off Wifi then turn it on. So I have to power cycle.

All this issue went away after turning off Wifi advanced option 'scanning always available'. I always have my Wifi turned on anyway. I suspected that Android 5.0.1 has an issue here, but some think it might be more device specific?

edit: To clarify further - the issue didn't totally go away, but it happens far less. And when it does happen, a simple Wifi turn off and turn on fixes it.

**Comment by adrian-bl** [comment]
Is this still an issue? I didn't see this on my device anymore after upgrading to 5.0.2

**Comment by sulemartin87** [comment]
I've used it for 5 hours now and not a single disconnection. I will continue testing this issue, but for now, all is well

**Comment by adrian-bl-yuga** [comment]
Closing this bug as android 5.0.2 fixed it for me

**Comment by sulemartin87** [comment]
Lucky for you, it just seemed to cure it for a bit for me. It happened a couple of times after 5.0.2 and I'm starting to consider it might be something else.

**Comment by sulemartin87** [comment]
turns out this bug still exists so i'll keep monitoring upcoming builds but for now i think i'll either move to your KitKat build or i'll just revert to stock, thank you.

**Comment by adrian-bl** [comment]
Hmm - it never happened to me on 5.0.2 :-/ but the next build will have wifi background scanning enabled, so it may improve the situation (it should be released in 1-2 days)
