### ISSUE TITLE
No network connection

### ISSUE THREAD

**Issue by c64bob** [adrian-bl-yuga/device-sony-c6603#25]
I can't get a network connection after flashing Android 5.0.1 - your version 5.0.6
I did a full wipe. APNs are set correctly. My baseband version is 9x15A-ACEFWMAZQ-30110098-72
Wifi is working without a problem.
Any ideas?

**Comment by adrian-bl-yuga** [comment]
You probably did not correctly configure your APN settings.

Closing this as this is a bugtracker (not a help forum).
