### ISSUE TITLE
Battery drain.

### ISSUE THREAD

**Issue by demonsked** [adrian-bl-yuga/device-sony-c6603#27]
I flashed this ROM on sunday. It was great for a two days. But now my battery is drain! Cell standby in top of battery usage - 41%!

**Comment by alex3305** [comment]
How's your signal strengh in your battery statistics?

**Comment by lxsameer** [comment]
I have the same issue

**Comment by adrian-bl** [comment]
Closing this issue: There is not enough information and the switch to hammerheads netmgr blobs seems to  have improved the battery life
