### ISSUE TITLE
Can't click the notifications that appear when screen on

### ISSUE THREAD

**Issue by AnterDogan** [adrian-bl-yuga/device-sony-c6603#28]
When I receive a call while doing something on my phone on top appears a white bar, where I can accept the call. But when I click on that, nothing happens

I'm talking about this notifications. They aren't "clickable"
http://www.androidpolice.com/wp-content/uploads/2014/11/nexus2cee_headsup_thumb.jpg

I am on 5.0.6. On 5.0.5 and 5.0.4 it worked like a charm!

**Comment by alex3305** [comment]
I've read somewhere (can't find the source atm) that there is a bug in Lollipop when your keyboard is open and you receive a call, you cannot accept is. Could you maybe test this?

**Comment by AnterDogan** [comment]
Well that's strange. All of a sudden everything works fine again. Doesn't matter if keyboard is on or not... I'll let you know when I can spot how the bug occurs

**Comment by adrian-bl-yuga** [comment]
works for me - but as alex3305 said: this might be a bug in lollipop (android 5.0 is VERY buggy!)

closing the bug as it is not device specific (and it will be fixed it google fixes it in AOSP)
