### ISSUE TITLE
touch screen freeze

### ISSUE THREAD

**Issue by AdmiralRedRum** [adrian-bl-yuga/device-sony-c6603#3]
When double tap to wake is enable, the touch screen will sometimes freeze when you turn on the device using power button (not sure about turning on using dtw itself). I've experienced this problem before in 4.3 using a custom kernel. This seems somewhat similar. The screen just freezes. I'm currently not rooted nor am I using other kernels. (Latest lollipop build, previous build had that freeze too)

**Comment by adrian-bl-yuga** [comment]
I know, this is actually a bug in the touchscreen panel itself and we will be unlikely to fix this.

Maybe the Settings menu should show a warning while enabling the feature.

**Comment by AdmiralRedRum** [comment]
Yeah, that would be nice. At least it prevents freaking out if it does happen.

**Comment by adrian-bl-yuga** [comment]
Added in: https://github.com/adrian-bl-yuga/android_packages_apps_Settings/commit/badc35d4d845b25b183781c5169c1c7fe92d44f3
