### ISSUE TITLE
 when it is off, my device automatically turn on

### ISSUE THREAD

**Issue by scalpell77** [adrian-bl-yuga/device-sony-c6603#30]
when I shut down my device and connect the charger when it is off, my device automatically turn on. How can i fix this?

**Comment by adrian-bl-yuga** [comment]
This is a known bug: the init script doesn't check the reboot reason (that said: showing the charger icon already has the full linux kernel running, so not booting the system doesn't really have a big advantage).

I'm unlikely to fix this bug myself as it doesn't bother me - but if someone sends me a patch i would be glad to include it.

**Comment by adrian-bl-yuga** [comment]
closing as 'wontfix' (but patches & pull requests would be welcome)
