### ISSUE TITLE
Only 3G by default

### ISSUE THREAD

**Issue by alex3305** [adrian-bl-yuga/device-sony-c6603#31]
By default only 3G is activated for the mobile data connection. Also after enabling 4G it seems that sometimes (idk what triggers it), the software reverts to 3G.

Did anyone else experience the same issue?

**Comment by adrian-bl** [comment]
No: Please show a screenshot from the '_#_#4636#_#_' menue

**Comment by alex3305** [comment]
Maybe it is because I dirty flashed a couple of versions (since 5.0.4). But the networktype is currently on LTE/GSM auto (PRL), Cellinfolistrate is at 2147483647 (int max), other settings are disabled.

**Comment by adrian-bl** [comment]
What happens if you force the phone to LTE only?

Also: what does 'adb logcat -b | grep "forcefully setting radio tech"' show?

[We are rewriting RADIO_TECH_DC_HSDPA to RADIO_TECH_HSPAP (as AOSP does not know about dualchannel HSDP+)]

**Comment by alex3305** [comment]
I didn't get any hits. I just reinstalled my phone, but I still don't have any service. Not on 2G/3G/4G. I'm going to revert to 5.0.7.

Edit: I found no differences. It still wouldn't work. I also tried with my gf's Xperia Z and she has just working 4G connection. Also tried downgrading to your 4.4.4 rom, which also didn't appear to work.

Maybe it has something to do with my phone or simcard. I will try to test it further tomorrow.

**Comment by adrian-bl** [comment]
What do you mean mit 'don't have any service' - so data doesn't work at all? even not in 2g mode?

I'm using 4G all the time and never had any issues, so yeh: it may be a problem with your hardware/operator.

You could also post the last few 100-lines of 'adb logcat -b radio', maybe this gives us some clue.
(Note that the output contains some semi-personal info: you may also mail it to me via adrian@blinkenlights.ch)

**Comment by alex3305** [comment]
Appearently it has to do something with my phone. I've been testing the last few days and it just seems that either my device or sim card is not working correctly; which results in the sim card not being recognized correctly...

I'm going to close this issue and sorry for the potential bother.

**Comment by adrian-bl** [comment]
AFAIK, the operator CAN restrict a phone to 3G using the SIM card (well: your contract), so it might be a good idea to verify this using some other phone.

But stupid question: You are sure that you got an C6603 and NOT a C6602 ? ;-)

**Comment by alex3305** [comment]
That's not the problem. I have 4G in quite a lot of places but sometimes my phone just randomly returns to WCDMA preferred / 3G or even No Service / Only Emergency Calls. I guess it's just an issue with my phone or simcard. 

And yes I have a C6603 :laughing:
