### ISSUE TITLE
wifi fail with PEAP

### ISSUE THREAD

**Issue by planarteapot** [adrian-bl-yuga/device-sony-c6603#33]
My wifi works fine at home, with two access points, each on a different sub-band.

At work, I can not connect to the Wifi. It used to be fine, before 5.0.7. My work Wifi uses PEAP.

My friendly IT dude show me the logs at his end. My phone attempts to authenticate, and a successful reply is sent back to it, but it seems to time out and fail.

**Comment by adrian-bl** [comment]
So it did work (using exactly the same configuration) on 5.0.6?
Do you remember if it still worked on 5.0.5 and 5.0.4?

There have been some WIFI changes and it may very well be possible that something broke.
This is the wifi-related-changes timeline:
1. Nov: 5.0.5  Switched to a newer WIFI Driver using the CAF settings
2. Dec: 5.0.6  No wifi changes
3. Dec: 5.0.7  Switched back to the old WIFI driver and use sonys wifi settings

So either the older driver or sonys WIFI settings broke it (or google did break it in android itself)

Could you please give this version a try: 
https://mega.co.nz/#!C9d1DAKQ!3OBPNtwldXulpKyPfN5a0EgQOdj39Tti21rj0yEtd74 ?
(You can flash it over 5.0.8 - going back to the 'real' 5.0.8 also isn't an issue)

This release includes the newer WIFI driver with sonys settings: So if this version works, something is wrong with the older driver.

If this version also does NOT work, you could try to replace /system/etc/firmware/wlan/prima/WCNSS_qcom_cfg.ini with this version:

https://raw.githubusercontent.com/adrian-bl-yuga/yuga-blobs-a806/928f234089784d9fa4d76aaa15b509f1780c71d6/system/etc/firmware/wlan/prima/WCNSS_qcom_cfg.ini

This is the WIFI config we used in 5.0.6. If this also fails, then it is googles fault ;-)

**Comment by planarteapot** [comment]
Tried the first one so far, nwifi.zip - no joy. Flashed it, rebooted, no connect, forget network, rejoin, tries but just says "Saved", no connect, powered off, powered on, no connect. Just sits there as "Saved".

ps. I hazily remember it to mostly work on 5.0.6 and before. Will verify.

**Comment by planarteapot** [comment]
OK, I put the new .ini file on top of {the nwifi.zip modified 5.0.8} and now my office wifi works!

**Comment by adrian-bl** [comment]
Ok, thanks a lot for testing this!

I'm actually very surprised that it was sonys own configuration that broke it.

But in this case i'll just switch back to qualcomms default config.
