### ISSUE TITLE
Performance suggestions

### ISSUE THREAD

**Issue by patrick-brigel** [adrian-bl-yuga/device-sony-c6603#39]
I compared the performance of this ROM with the stock ROM used on my Nexus 4 running 5.0.1. Both devices have similar specs. However, the Z has a 1080p resolution, which should lead to a higher GPU usage, I guess.

The first thing I noticed was the fast enabling and disabling of CPU cores on the Nexus 4.

E.g.: I woke it up, had still CPU-Z running in background and it nearly instantly enabled all four cores. Some sec later it disabled 3 of the 4 cores while nothing much happened. As I pulled down the notification center 3 of 4 cores got activated and where disabled seconds later, after I stopped pulling it. Same goes with the frequency. The N4 uses the ondemand governor.
Well, while the Z, running your ROM, just starts enabling or disabling the cores, when the performance needed is constantly high over a given time period.

I made the same "test" with the Z, which I made with the N4 and it "stuck" in only using one core with 1512MHz. After pulling the notification center up and down over time it enabled the second core and so on ad nauseam. I stopped pulling the notification center and it needed like 10 sec to disable to 4th. core and another 10 sec to disable the 3rd one, while every core was on 384MHz.
And as I said, same goes for the frequency.

To me it looks like, the events to enable or disable a core or to set a decent frequency are triggered to late respectively not fast enough to provide a smooth performance.

**Comment by adrian-bl-yuga** [comment]
This is the intended behaviour: qc-fqd is _very_ conservative at enabling new cores and will only do so if all online cores were busy for a few seconds AND the run-queue is > $number_online_cores.

You can set the min. number of cores to keep online in the 'Xperia Z Settings' menu: I'm usually running with 2 always-on cores.
