### ISSUE TITLE
Missing translation in xperia z settings

### ISSUE THREAD

**Issue by wanhuan** [adrian-bl-yuga/device-sony-c6603#4]
Hi,pabx!
I have translated the xperia z settings menu into Chinese, but I'm not sure will it works, can you have a look at it?
btw,what is msgid in the strings.xml and how can I generate it?
thanks.
https://github.com/wanhuan/android_packages_apps_Settings/commit/97e2f886df614992b8862a6fda8f8883e8ff0353

**Comment by adrian-bl-yuga** [comment]
Thanks a lot! I merged your changes in https://github.com/adrian-bl-yuga/android_packages_apps_Settings/commits/lp50

The msgid value is not needed: It is just a way to hardcode the resource-id of a string and is not required in this case.
