### ISSUE TITLE
Battery stats

### ISSUE THREAD

**Issue by jpacho89** [adrian-bl-yuga/device-sony-c6603#40]
Hello Adrian,
Congrats for your ROM, it has the best performance in my Xperia Z for sure. I only noticed a little problem, when I look batery stats I noticed a big drop by Miscelanious ("Varios" in Spanish in the screenshot), more than double the screen consuption. Please take a look at the screenshots, maybe my battery is not in good conditions and needs to be replaced, or maybe this stats are completely normal. Thanks!

https://docs.google.com/file/d/0B41kk1VErSamUUJJZnlSeTg1VUE/edit?usp=docslist_api

https://docs.google.com/file/d/0B41kk1VErSamRG5qbkdiV09uQU0/edit?usp=docslist_api

https://docs.google.com/file/d/0B41kk1VErSamU3BBVGVQWTNyZTA/edit?usp=docslist_api

**Comment by adrian-bl** [comment]
This is a known issue but pretty hard to reproduce: Sometimes, the ROM uses far too much power in deep sleep.

I'm 80% sure that this is the fault of the baseband: You can reboot it (without rebooting the phone) by going into Settings -> Device Settings -> Restart baseband processor

This usually cures the drain for me. I'm currently running some tests with a new baseband version that might cure the issue (hopefully)

**Comment by jpacho89** [comment]
Thanks mate!
Will give it a try and send you feedback.

**Comment by jpacho89** [comment]
I have been using the phone for a day alfter restarting baseband, but miscellaneous battery consuption is still there. It drops 51% of the battery, when screen uses only 29%. Maybe I need another baseband optimized for my location? Thanks!

**Comment by jpacho89** [comment]
After flashing patched 5.1 "Miscelaneous" battery drop seems to have dissapeared. Excellent job Adrian, best ROM ever for yuga!
