### ISSUE TITLE
Music volume popup

### ISSUE THREAD

**Issue by rsmything** [adrian-bl-yuga/device-sony-c6603#42]
Good day,
when i press volume down/up key during music play "volume popup" doesn't show animation after 1st pressing the key

Version 5.1.0-p1 (Released 2015-03-24)
![screenshot_2015-03-30-18-13-21](https://cloud.githubusercontent.com/assets/11719983/6896854/dfb1f6ac-d708-11e4-9a3f-19b16cc28393.png)

**Comment by adrian-bl-yuga** [comment]
There is nothing wrong with this: This is the standard AOSP behaviour

**Comment by rsmything** [comment]
But it woks fine in the your first release 5.1(2015-03-12)
