### ISSUE TITLE
Suggestion: Replace Cyanogenmods fork browser with Firefox (Beta?)

### ISSUE THREAD

**Issue by Centril** [adrian-bl-yuga/device-sony-c6603#46]
Wouldn't it be totally awesome if the preinstalled browser would be Mozilla Firefox (Beta?)...?
After all, it is such an outstanding and lovely browser.

**Comment by adrian-bl-yuga** [comment]
Firefox is available from f-droid and the play store.
There is no need to bundle it and including it in the rom would mean that it would fail to get updates from the play store + f-droid (due to the different signature)
