### ISSUE TITLE
Apps Crashing after using it after 2 3 days :(

### ISSUE THREAD

**Issue by prathamsbapat** [adrian-bl-yuga/device-sony-c6603#49]
Apps Crashing after using it after 2 3 days :(

**Comment by adrian-bl-yuga** [comment]
Sorry, but such a bugreport has 0 value:
- I use the ROM daily, and there are no mysterious crashes
- You provided no logcat nor did you tell us what apps are crashing (but in any case: it is probably the fault of the app)

**Comment by prathamsbapat** [comment]
i have reflashed the rom on my device 
using it since 10 hrs now
incase if this occurs, will send you the bug report
