### ISSUE TITLE
media volume bug

### ISSUE THREAD

**Issue by AdmiralRedRum** [adrian-bl-yuga/device-sony-c6603#5]
Media volume can only be controlled by rockers. Doesn't respond to touch when the "slider" appear from the notifications area. Also, the slider doesn't move even when the rockers are pressed. Easiest way to check in my case is to play some music, go to settings, go to sounds, then hit the volume rocker, the bar in the settings moves, but the one from the notification only refreshes if it disappears/reappears.

**Comment by adrian-bl** [comment]
This works perfectly for me while playing music.

Are you connected to a bluetooth headset?

**Comment by AdmiralRedRum** [comment]
Oh this is weird, after like 5 or 6 reboots its working again. I guess this issue can be closed.
