### ISSUE TITLE
Missing Notifications since update from 5.0.0 to 5.0.3

### ISSUE THREAD

**Issue by G3rtz** [adrian-bl-yuga/device-sony-c6603#7]
I had a nearly flawless experience on 5.0.0, except the NFC Problems, which occoured.
So naturally i upgraded to 5.0.3 and since this update (Sunday night) i am no longer able to receive push notifications.. i have to manually open the apps (in my case its gmail, threema, and pushbullet).
When you need a log, i will provide one. atm there is no log, i have to make one.

**Comment by adrian-bl-yuga** [comment]
This sounds like an incomplete gapps installation:

Are you sure that the gapps package got reinstalled after the upgrade?
Eg: did you keep the gapps package in /sdcard or did you re-install it using CWM?

**Comment by G3rtz** [comment]
I installed the package using CWM.. How can i install your Package, now that i already have gapps?
Alternativly i am now trying the PA-Gapps and reporting back asap.
Thanks for the suggestion, though.

**Comment by alex3305** [comment]
I had problems regarding push notifications from the start (5.0.1 for me). I installed Gapps from /sdcard/ as you recommended and even tried reïnstalling them by deleting the gapps install file. Unfortunately it didn't resolve anything for me.

For me the issue with Hangouts and E-mail is the worst, Whatsapp notifications are getting delayed by a couple of hours. When opening the app everything seems alright though. I don't even have any issues with syncing whatsoever.

**Comment by alex3305** [comment]
I just re-installed Gapps by deleting `GoogleOneTimeInitializer.apk` If you want to do it yourself it is quite easy, just connect your phone through adb and follow the following steps:

```
adb shell mount -o remount,rw /system
adb shell rm -f /system/priv-app/GoogleOneTimeInitializer/GoogleOneTimeInitializer.apk
adb reboot
```

After which the gapps should be automatically reinstall itself. Although I don't really know what could cause this. Maybe leaving the gapps on the sdcard when upgrading the system?

**Comment by G3rtz** [comment]
I have now tried the same. But my notifications still don't work.

**Comment by adrian-bl-yuga** [comment]
WhatsApp works perfectly for me: Does this happen while you are connected via WIFI or 4G?

**Comment by alex3305** [comment]
For me it was both.

**Comment by G3rtz** [comment]
for me, too. my problem exists primary with threema, pushbullet and gmail/inbox. both don't have a connection... when i open threema, it connects a get a ton of messages. same for pushbullet. With Gmail/Inbox i have to swipe down.

**Comment by adrian-bl-yuga** [comment]
Ok, i think i tracked this down: Turns out that the gapps package from 'basketbuild' is utter crap (why does everything even remotely related to cyanogenmod suck so hard?!)

I've built my own gapps package (using the nexus 7 factory image) and gmail sync works now fine.

**Comment by alex3305** [comment]
Because CM is becoming a commercial enterprise, although they deny it. There is a reason why people such as Andrew Dodd started OmniROM. Although I don't really see that project getting any reasonable traction whatsoever. 

Anyway, glad you took the time and effort to find the issue and fix it.

**Comment by G3rtz** [comment]
Thank you very much.
i contacted you on g+ yesterday, but i tested some things for myself.. this is just fyi: i took the latest basketbuild, and wiped my cache partition, which partially did the job... gmail didn't work, but threema and pushbullet are working fine now. with the next update, i am going to install your package. :) Thank you again.

**Comment by adrian-bl-yuga** [comment]
Ok, i would be glad if someone could verify that this solves the issue:

Step 1: Download all 3 files from https://mega.co.nz/#F!O8Vg0bjS!NE8aCyRG6_Zdrn3dXXGFfw
Step 2: Push the NEW gapps package to /sdcard/ (you can remove the oldone if you like)
Step 3: Flash boot.img and system.img

Your phone will now hopefully boot up without any FCs (but note: the new gapps package does not include the google-launcher. You can download it from the market if you need it)

Now go to Settings -> Accounts and ensure that gmail sync is enabled.

This fixed the gmail issue for me: E-Mails are now pushed to the phone in less than 30 seconds and WhatsApp still works with a delay of 3-5 seconds (if the phone is deep sleeping)

**Comment by alex3305** [comment]
Just flashed it and Play Services FC'ed on me constantly. Tried to delete the app data and even the app updates but it didn't help. Now my phone just gives me a black screen upon entering Android. 

I'm going to do a factory reset and see how it goes. 

Edit: everything seems to work after the factory reset. Will report back in a bit.

**Comment by adrian-bl-yuga** [comment]
@alex3305 Are you still happy with the new gapps package after a factory reset?

I upgraded my daily-use phone yesterday and also had to do a full wipe (while the upgrade worked without a wipe on my test-phone :-/ ), so it seems that there is no sane way to migrate existing installations to the new gapps package.

But if everything works for you with the new package, i would just bite the bullet and have people require to do a full wipe on the next upgrade.

**Comment by alex3305** [comment]
@adrian-bl-yuga Notifications seem to be working now albeit sometimes a bit slow. But that can also be a signal problem though...

I personally think the new gapps are the way too go. The only thing missing is the Google Keyboard 4, which is not yet available from the Play Store. I downloaded the version from apkmirror (which is from Android Police). This is a minor issue though, but maybe something you can consider adding.

**Comment by adrian-bl-yuga** [comment]
@alex3305 Ok, thanks a lot for testing this!
The delay is probably on googles side (or due to Android 5.0 as it tries very hard to group wake-ups together) but the old gapps package really was broken while the new version seems to be ok (no more authentication errors in the log)

I also upgraded the gapps package to include the google keyboard (thanks for the hint) and will release 5.0.4 in a few minutes.
