### ISSUE TITLE
Echo issue on calls

### ISSUE THREAD

**Issue by vchiotelis** [adrian-bl-yuga/device-sony-c6603#8]
From the first rom 5.0 I'm facing issue with the echo when I perform calls.
The partner from the other side hears his echo. 
Εverything works perfect with headphones.
Also I can provide you logcat if need it.

**Comment by SuperShaman67** [comment]
I can confirm this issue.

**Comment by vchiotelis** [comment]
I have manage to get a new logcat from my phone with the latest boot image 5.0.3b.
I have upload the log at the below link.

https://www.mediafire.com/?qsndu7f1lvr1s76

In the log i have perform two phonecalls, one without headset and one with headset.

**Comment by adrian-bl-yuga** [comment]
Unfortunately a logcat will not help in this case as i am simply not able to reproduce this problem.

I already did multiple phone calls and so far nobody complained (i even phoned myself a few times and there was no echo).

Did this also happen on my 4.4.4 Release (http://www.blinkenlights.ch/ccms/android/yuga.html) or/and what ROM were you running before my 5.0 build? (where i assume that the issue did not exist?)

**Comment by vchiotelis** [comment]
No this doesn't happen on official rom 4.4.4 .283.
I have also test it. I have roll back the phone on official kitkat and everithing works ok no echo.
Later on I will try your 4.4.4 kitkat release and I will lets you know if I have any issue.

**Comment by vchiotelis** [comment]
I have also flash your rom Android 4.4 for Sony Xperia Z (YUGA) and I have the same issue with the echo.
I flash back the official kitkat rom 4.4.4 283.
I have perform some tests with the official Sony rom and there is no echo on calls.
Also I have check the audio_policy.confg and I notes that they have perform many changes there. Do you believe that if we apply the same change at you rom audio_policy.confg may fix the issue?

**Comment by vchiotelis** [comment]
I'm investigating this issue and later on I will flash again your Android 5 rom 5.0.3 in order to perform some tests.
First I will try to replace audio_policy.conf and audio_effects.conf with the conf files from Sony official kitkat rom.
If this not works I will try to add on Android 5 audio_effects.conf the below line for noise suppression.

pre_processing {
  voice_communication {
    aec {}
    ns {}
   } 
}

I will lets you know with the results of all above tests.

**Comment by adrian-bl-yuga** [comment]
What happens if you do:

```
adb shell
setprop persist.audio.fluence.voicecall true
setprop persist.audio.dualmic.config endfire       
reboot
```

? Does it make any difference?

**Comment by vchiotelis** [comment]
Sorry I haven't try anything. 
I will try today and I will post the results.

**Comment by vchiotelis** [comment]
I flash the latest rom and seems that everything its ok, no echo. I don't know the changes but now works ok.

**Comment by adrian-bl** [comment]
ok great! thanks for verifying this
