### ISSUE TITLE
Android Keyboard Gesture Typing

### ISSUE THREAD

**Issue by slovenec88** [adrian-bl-yuga/device-sony-c6603#9]
Gesture typing not working on English (US), and probably other languages.
What I already tried:
- reflash
- clear data

I think it's a gapps issue, but didn't try other than attached to blinkenlights.ch

**Comment by adrian-bl-yuga** [comment]
Gesture Typing was never present in the AOSP keyboard.
You must install the Google Keyboard (available from the market) if you want to use this feature.

**Comment by slovenec88** [comment]
It is present in the menus of aosp keyboard. Thank you. Google keyboard works great.
